# Welcome to Jekyll!

# Website settings
title: 邓小帅的进阶之路
description: dengsir's blog
keywords: dengsir,邓小帅,blog,Jekyll,github
baseurl:  /blog # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://dengkairong.github.io/blog  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /blog/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: 邓小帅  # Be used at blog posts' author.
  first_name: kairong  # Be used at index page about me section.
  last_name: deng  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: dengkairong  # Leave blank if you don't have now
  #linkedin_id: kun-jia-991264a2 # Leave blank if you don't have now
  #facebook_username: jiakunnj  # Leave blank if you don't have now
  #twitter_username: jiakun614  # Leave blank if you don't have now
  email: dengsir058@qq.com # Leave blank if you don't have now
  #cv: http://cv.jarrekk.com  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: 一介思想放荡不羁、代码闷骚风流的iOS开发者罢了、  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: 邓小帅
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
